apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  labels:
    app: logging-view-plugin
    app.kubernetes.io/created-by: openshift-logging_instance
    app.kubernetes.io/name: logging-view-plugin
  name: logging-view-plugin
spec:
  displayName: Logging Console Plugin
  proxy:
    - alias: backend
      authorize: true
      service:
        name: logging-loki-gateway-http
        namespace: openshift-logging
        port: 8080
      type: Service
  service:
    basePath: /
    name: logging-view-plugin
    namespace: openshift-logging
    port: 9443
