apiVersion: v1
data:
  access_key_id: "{{ aws_access_key_id_b64 }}"
  access_key_secret: "{{ aws_secret_access_key_b64 }}"
  bucketnames: "{{ bucketnames_b64 }}"
  endpoint: "{{ endpoint_b64 }}"
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
type: Opaque
