apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: AlertingRule.v1beta1.loki.grafana.com,Elasticsearch.v1.logging.openshift.io,Kibana.v1.logging.openshift.io,LokiStack.v1.loki.grafana.com,RecordingRule.v1beta1.loki.grafana.com,RulerConfig.v1beta1.loki.grafana.com
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat
spec:
  upgradeStrategy: Default
